const KEY="acs_sgc_v11";
const ALT_FRICTION=[1000,2000,3000,5000,10000,15000,20000];
const ALT_SCALE=[-1000,0,500,1000,1500,2000,3000,4000,6000,8000,10000,12000,14000,16000,18000,20000];
const FRICTION_TOL=[70,70,70,70,70,80,90];
const SCALE_TOL=[20,20,20,20,25,30,30,35,40,60,80,90,100,110,120,130];
const BARO=[["28,10 / 951,6",-1727],["28,50 / 965,1",-1340],["29,00 / 982,1",-863],["29,50 / 999,00",-392],["29,92 / 1013,25",0],["30,50 / 1032,90",531],["30,90 / 1046,40",893],["30,99 / 1049,50",974]];
const INT_ALT=[-1000,0,1000,2000,4000,6000,8000,10000,12000,14000,16000,18000,20000];
const ENC_NOM=[-950,-50,950,1950,3950,5950,7950,9950,11950,13950,15950,17950,19950];

let db=loadDB();
let currentId=null;
let currentReport="altimetro";

function uid(){return "S"+Date.now().toString(36)+Math.random().toString(36).slice(2,7).toUpperCase()}
function loadDB(){try{return JSON.parse(localStorage.getItem(KEY))||{sessions:[]}}catch(e){return {sessions:[]}}}
function saveDB(){localStorage.setItem(KEY,JSON.stringify(db));updateDashboard();renderSessions()}
function blankSession(){return {id:uid(),status:"Rascunho",createdAt:new Date().toISOString(),meta:{os:"",data:new Date().toISOString().slice(0,10),cliente:"",validade:"2 anos",fabricante:"",pn:"",sn:"",prefixo:"",tecnico:""},reports:{altimetro:{friction:ALT_FRICTION.map(()=>({sem:"",com:""})),scale:ALT_SCALE.map(()=>({lido:""})),leak:{pressao:"14,942",lido:""},baro:BARO.map(x=>({valor:x[0],diferenca:x[1],lido:""})),hyst:[{lidoDec:"",lidoCresc:"",dif:"0"},{lidoDec:"",lidoCresc:"",dif:"0"}]},integracao:INT_ALT.map((a,i)=>({teste:i+1,altitude:a,altimetro:"",transponder:""})),encoder:ENC_NOM.map((n,i)=>({teste:i+1,altitude:INT_ALT[i],nominal:n,atual:""})),transponder:{radio:[["Frequência de transmissão ATCBRS","1093 ≥ frequência ≥ 1087",""],["Frequência de transmissão Mode S classes 1B, 2B e 3B","1093 ≥ frequência ≥ 1087",""],["Mode S 1B/2B/3B opcional 1090 ±1 MHz","1091 ≥ frequência ≥ 1089",""],["Mode S classes 1A/2A/3A/4A","1091 ≥ frequência ≥ 1089",""]],power:[["ATCBRS classes 1A e 2A","Potência ≥ 125 W",""],["ATCBRS classes 1B e 2B","Potência ≥ 70 W",""],["Mode S classes 1A,2A,3A e 4A","Potência ≥ 125 W",""],["Mode S classes 1B,2B e 3B","Potência ≥ 70 W",""],["ATCBRS e Mode S todas as classes","Potência ≥ 500 W",""]],suppression:"",sensitivity:"",other:[["Frequência de recepção","1030 MHz","1030 MHz"],["Largura de pulso F1","0,45 µs ± 0,1 µs",""],["Largura de pulso F2","0,45 µs ± 0,1 µs",""],["Espaçamento entre F1 e F2","20,30 µs ± 0,1 µs",""]],modeS:[["Isolamento de canais","Potência da antena selecionada ≥ 20 dB",""],["Endereço do Mode S","Interrogar com 1 endereço correto e pelo menos dois errados...",""],["Formato do Mode S","Interrogar com os formatos UF para os quais está equipado...",""],["Interrogação Mode S All Call","UF=11 e ATCBRS Mode S All Call; verificar DF=11",""],["Interrogação ATCBRS All Call","Nenhuma resposta deve ser gerada",""],["Squitter","Gerado na razão de 1 por segundo",""]]}}}}

function newSession(){currentId=null;fillSession(blankSession());showView("session")}
function getCurrent(){return db.sessions.find(s=>s.id===currentId)}
function fillSession(s){currentId=s.id; set("os",s.meta.os);set("data",s.meta.data);set("cliente",s.meta.cliente);set("validade",s.meta.validade);set("fabricante",s.meta.fabricante);set("pn",s.meta.pn);set("sn",s.meta.sn);set("prefixo",s.meta.prefixo);set("tecnico",s.meta.tecnico);document.getElementById("sessionTitle").textContent=s.meta.os?`Sessão OS ${s.meta.os}`:"Nova sessão de calibração";document.getElementById("sessionStatus").textContent=s.status;renderAllTables(s)}
function collectMeta(s){["os","data","cliente","validade","fabricante","pn","sn","prefixo","tecnico"].forEach(k=>s.meta[k]=document.getElementById(k).value.trim())}
function saveCurrent(finalize=false){let s=getCurrent();if(!s){s=blankSession();currentId=s.id;db.sessions.push(s)}collectMeta(s);s.status=finalize?"Finalizada":"Rascunho";s.updatedAt=new Date().toISOString();collectTables(s);saveDB();document.getElementById("sessionStatus").textContent=s.status;document.getElementById("sessionTitle").textContent=s.meta.os?`Sessão OS ${s.meta.os}`:"Sessão de calibração";alert(finalize?"Sessão finalizada e salva offline.":"Rascunho salvo offline.")}
function collectTables(s){
  document.querySelectorAll("[data-r='friction']").forEach(el=>s.reports.altimetro.friction[+el.dataset.i][el.dataset.k]=el.value);
  document.querySelectorAll("[data-r='scale']").forEach(el=>s.reports.altimetro.scale[+el.dataset.i].lido=el.value);
  document.querySelectorAll("[data-r='leak']").forEach(el=>s.reports.altimetro.leak.lido=el.value);
  document.querySelectorAll("[data-r='baro']").forEach(el=>s.reports.altimetro.baro[+el.dataset.i].lido=el.value);
  document.querySelectorAll("[data-r='hyst']").forEach(el=>s.reports.altimetro.hyst[+el.dataset.i][el.dataset.k]=el.value);
  document.querySelectorAll("[data-r='int']").forEach(el=>s.reports.integracao[+el.dataset.i][el.dataset.k]=el.value);
  document.querySelectorAll("[data-r='enc']").forEach(el=>s.reports.encoder[+el.dataset.i].atual=el.value);
  document.querySelectorAll("[data-r='tp']").forEach(el=>setNested(s.reports.transponder,el.dataset.path,el.value));
}
function setNested(o,path,v){let a=path.split(".");let x=o;for(let i=0;i<a.length-1;i++)x=x[a[i]];x[a[a.length-1]]=v}
function set(id,v){document.getElementById(id).value=v||""}

function renderAllTables(s){renderFriction(s);renderScale(s);renderLeak(s);renderBaro(s);renderHyst(s);renderIntegration(s);renderEncoder(s);renderTransponder(s)}
function inp(v,attrs=""){return `<input class="cell" value="${esc(v)}" ${attrs}>`}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function wrap(h){return `<div class="table-wrap">${h}</div>`}
function renderFriction(s){let h="<table class='data-table'><thead><tr><th>Altitude (pés)</th><th>Valor sem vibração</th><th>Valor com vibração</th><th>Tolerância</th></tr></thead><tbody>";ALT_FRICTION.forEach((a,i)=>h+=`<tr><td>${a}</td><td>${inp(s.reports.altimetro.friction[i].sem,`data-r="friction" data-i="${i}" data-k="sem"`)}</td><td>${inp(s.reports.altimetro.friction[i].com,`data-r="friction" data-i="${i}" data-k="com"`)}</td><td>${FRICTION_TOL[i]}</td></tr>`);document.getElementById("frictionTable").innerHTML=wrap(h+"</tbody></table>")}
function renderScale(s){let h="<table class='data-table'><thead><tr><th>Altitude (pés)</th><th>Pressão equivalente (pol Hg)</th><th>Valor lido</th><th>Tolerância ± pés</th></tr></thead><tbody>";const p=["31,018","29,921","29,385","28,856","28,335","27,821","26,817","25,842","23,978","22,225","20,577","19,029","17,577","16,216","14,942","13,75"];ALT_SCALE.forEach((a,i)=>h+=`<tr><td>${a}</td><td>${p[i]}</td><td>${inp(s.reports.altimetro.scale[i].lido,`data-r="scale" data-i="${i}"`)}</td><td>${SCALE_TOL[i]}</td></tr>`);document.getElementById("scaleTable").innerHTML=wrap(h+"</tbody></table>")}
function renderLeak(s){document.getElementById("leakTable").innerHTML=wrap(`<table class='data-table'><thead><tr><th>Pressão (In HG)</th><th>Altitude</th><th>Valor lido</th><th>Tol. ± pés</th></tr></thead><tbody><tr><td>${s.reports.altimetro.leak.pressao}</td><td>18000</td><td>${inp(s.reports.altimetro.leak.lido,`data-r="leak"`)}</td><td>100</td></tr></tbody></table>`)}
function renderBaro(s){let h="<table class='data-table'><thead><tr><th>Pressão</th><th>Diferença de altitude</th><th>Valor lido</th></tr></thead><tbody>";s.reports.altimetro.baro.forEach((r,i)=>h+=`<tr><td>${r.valor}</td><td>${r.diferenca}</td><td>${inp(r.lido,`data-r="baro" data-i="${i}"`)}</td></tr>`);document.getElementById("baroTable").innerHTML=wrap(h+"</tbody></table>")}
function renderHyst(s){let h="<table class='data-table'><thead><tr><th>Ponto de teste</th><th>Valor lido (decrescente)</th><th>Valor lido (crescente)</th><th>Diferença</th><th>Tolerância</th></tr></thead><tbody>";[["1º ponto — 50% altitude máxima (10000 pés)",75],["2º ponto — 40% altitude máxima (8000 pés)",75]].forEach((r,i)=>h+=`<tr><td>${r[0]}</td><td>${inp(s.reports.altimetro.hyst[i].lidoDec,`data-r="hyst" data-i="${i}" data-k="lidoDec"`)}</td><td>${inp(s.reports.altimetro.hyst[i].lidoCresc,`data-r="hyst" data-i="${i}" data-k="lidoCresc"`)}</td><td>${inp(s.reports.altimetro.hyst[i].dif,`data-r="hyst" data-i="${i}" data-k="dif"`)}</td><td>${r[1]}</td></tr>`);document.getElementById("hystTable").innerHTML=wrap(h+"</tbody></table>")}
function renderIntegration(s){let h="<table class='data-table'><thead><tr><th>Teste</th><th>Altitude (pés)</th><th>Leitura do altímetro</th><th>Leitura do transponder</th></tr></thead><tbody>";s.reports.integracao.forEach((r,i)=>h+=`<tr><td>${r.teste}</td><td>${r.altitude}</td><td>${inp(r.altimetro,`data-r="int" data-i="${i}" data-k="altimetro"`)}</td><td>${inp(r.transponder,`data-r="int" data-i="${i}" data-k="transponder"`)}</td></tr>`);document.getElementById("integrationTable").innerHTML=wrap(h+"</tbody></table>")}
function renderEncoder(s){let h="<table class='data-table'><thead><tr><th>Teste</th><th>Altitude (pés)</th><th>Ponto de transição nominal</th><th>Ponto de transição atual</th></tr></thead><tbody>";s.reports.encoder.forEach((r,i)=>h+=`<tr><td>${r.teste}</td><td>${r.altitude}</td><td>${r.nominal}</td><td>${inp(r.atual,`data-r="enc" data-i="${i}"`)}</td></tr>`);document.getElementById("encoderTable").innerHTML=wrap(h+"</tbody></table>")}
function renderTransponder(s){let t=s.reports.transponder;let h=`<div class="field-grid"><div class="field full"><b>Rádio frequência de resposta</b></div>`;t.radio.forEach((r,i)=>h+=`<div class="field full"><label>${r[0]}<input data-r="tp" data-path="radio.${i}.2" value="${esc(r[2])}" placeholder="Valor encontrado"></label></div>`);h+=`<div class="field full"><b>Potência de pico de saída de RF</b></div>`;t.power.forEach((r,i)=>h+=`<div class="field full"><label>${r[0]} — ${r[1]}<input data-r="tp" data-path="power.${i}.2" value="${esc(r[2])}" placeholder="Valor encontrado (W)"></label></div>`);h+=`<div class="field"><label>Supressão Modo A<textarea data-r="tp" data-path="suppression">${esc(t.suppression)}</textarea></label></div><div class="field"><label>Sensibilidade do receptor<textarea data-r="tp" data-path="sensitivity">${esc(t.sensitivity)}</textarea></label></div>`;h+=`<div class="field full"><b>Outras medições</b></div>`;t.other.forEach((r,i)=>h+=`<div class="field"><label>${r[0]}<small>Requerido: ${r[1]}</small><input data-r="tp" data-path="other.${i}.2" value="${esc(r[2])}"></label></div>`);h+=`<div class="field full"><b>Somente para Transponder Mode S</b></div>`;t.modeS.forEach((r,i)=>h+=`<div class="field full"><label>${r[0]}<small>${r[1]}</small><input data-r="tp" data-path="modeS.${i}.2" value="${esc(r[2])}"></label></div>`);document.getElementById("transponderForm").innerHTML=h+"</div>"}

function showView(v){document.querySelectorAll(".view").forEach(x=>x.classList.add("hidden"));document.getElementById("view-"+v).classList.remove("hidden");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.view===v));const titles={dashboard:["Dashboard","Gerenciamento de calibração"],session:["Nova Sessão","Preenchimento dos laudos"],sessions:["Sessões","Rascunhos e laudos finalizados"],backup:["Backup","Dados locais do SGC"]};document.getElementById("pageTitle").textContent=titles[v][0];document.getElementById("pageSub").textContent=titles[v][1]}
function updateDashboard(){let a=db.sessions;dashTotal.textContent=a.length;dashOpen.textContent=a.filter(s=>s.status!=="Finalizada").length;dashDone.textContent=a.filter(s=>s.status==="Finalizada").length;dashLast.textContent=a.length?(a[a.length-1].meta.os||"Sem OS"):"—";let recent=a.slice(-5).reverse();recentSessions.innerHTML=recent.length?recent.map(rowHtml).join(""):`<div class="empty">Nenhuma sessão cadastrada.</div>`}
function rowHtml(s){return `<div class="session-row"><div><b>OS ${esc(s.meta.os||"—")} — ${esc(s.meta.cliente||"Sem cliente")}</b><small>${esc(s.meta.prefixo||"Sem prefixo")} · ${s.status} · ${s.meta.data||""}</small></div><button class="secondary" onclick="openSession('${s.id}')">Abrir</button></div>`}
function renderSessions(){sessionsList.innerHTML=db.sessions.length?db.sessions.slice().reverse().map(rowHtml).join(""):`<div class="empty">Nenhuma sessão cadastrada.</div>`}
function openSession(id){let s=db.sessions.find(x=>x.id===id);if(!s)return;fillSession(s);showView("session")}
window.openSession=openSession;

function printReport(){let s=getCurrent();if(!s){alert("Salve a sessão antes de imprimir.");return}collectMeta(s);collectTables(s);saveDB();buildPrint(s);window.print()}
function metaHTML(s){let m=s.meta;return `<div class="print-meta"><div><b>Cliente:</b></div><div>${esc(m.cliente)}</div><div><b>Validade:</b></div><div>${esc(m.validade)}</div><div><b>OS:</b></div><div>${esc(m.os)}</div><div><b>DATA:</b></div><div>${esc(m.data)}</div><div><b>Fabricante:</b></div><div>${esc(m.fabricante)}</div><div><b>P/N:</b></div><div>${esc(m.pn)}</div><div><b>S/N:</b></div><div>${esc(m.sn)}</div><div><b>PREFIXO:</b></div><div>${esc(m.prefixo)}</div></div>`}
function pTable(headers,rows){return `<table class="print-table"><thead><tr>${headers.map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join("")}</tr>`).join("")}</tbody></table>`}
function buildPrint(s){
 let a=s.reports.altimetro,t=s.reports.transponder;
 let f=ALT_FRICTION.map((x,i)=>[x,a.friction[i].sem||"",a.friction[i].com||"",FRICTION_TOL[i]]);
 let sc=ALT_SCALE.map((x,i)=>[x,["31,018","29,921","29,385","28,856","28,335","27,821","26,817","25,842","23,978","22,225","20,577","19,029","17,577","16,216","14,942","13,75"][i],a.scale[i].lido||"",SCALE_TOL[i]]);
 let leak=[[a.leak.pressao,"18000",a.leak.lido||"","100"]];
 let bar=a.baro.map(r=>[r.valor,r.diferenca,r.lido||""]);
 let hy=[["1º — 50% altitude máxima (10000 pés)",a.hyst[0].lidoDec||"",a.hyst[0].lidoCresc||"",a.hyst[0].dif||"0","75"],["2º — 40% altitude máxima (8000 pés)",a.hyst[1].lidoDec||"",a.hyst[1].lidoCresc||"",a.hyst[1].dif||"0","75"]];
 let p1=`<div class="print-page"><div class="print-title">LAUDO TÉCNICO DO ALTÍMETRO</div>${metaHTML(s)}<div class="print-section">TESTE DE ATRITO (pressão decrescente)</div>${pTable(["ALTITUDE (PÉS)","VALOR SEM VIBRAÇÃO","VALOR COM VIBRAÇÃO","TOLERÂNCIA ESPECÍFICA (PÉS)"],f)}<div class="print-section">ERRO DE ESCALA (pressão decrescente)</div>${pTable(["ALTITUDE (PÉS)","PRESSÃO EQUIVALENTE (POL HG)","VALOR LIDO","TOLERÂNCIA ± PÉS"],sc)}<div class="print-grid2"><div><div class="print-section">VAZAMENTO DE CAIXA</div>${pTable(["PRESSÃO (IN HG)","ALTITUDE","VALOR LIDO","TOL. ±"],leak)}</div><div><div class="print-section">ERRO DE ESCALA BARÔMETRO (tol. ±25 pés)</div>${pTable(["PRESSÃO","DIFERENÇA","VALOR LIDO"],bar)}</div></div><div class="print-section">HISTERESE (Altitude máxima de operação — pressão crescente)</div>${pTable(["PONTO DE TESTE","VALOR DECRESCENTE","VALOR CRESCENTE","DIFERENÇA","TOLERÂNCIA"],hy)}<div class="sig"><div>Responsável técnico</div><div>Cliente</div></div></div>`;
 let ir=s.reports.integracao.map(r=>[r.teste,r.altitude,r.altimetro||"",r.transponder||""]);
 let p2=`<div class="print-page"><div class="print-title">LAUDO TÉCNICO INTEGRAÇÃO DO TRANSPONDER E ALTITUDE ENCODER</div>${metaHTML(s)}<div class="print-left"><div class="print-section">Verificação da altitude transmitida pelo transponder</div>${pTable(["TESTE Nº","ALTITUDE (PÉS)","LEITURA DO ALTÍMETRO (PÉS)","LEITURA DO TRANSPONDER (PÉS)"],ir)}</div><div class="sig"><div>Responsável técnico</div><div>Cliente</div></div></div>`;
 let er=s.reports.encoder.map(r=>[r.teste,r.altitude,r.nominal,r.atual||""]);
 let p3=`<div class="print-page"><div class="print-title">LAUDO TÉCNICO DO ENCODER</div>${metaHTML(s)}<div class="print-left"><div class="print-section">Verificação da altitude transmitida pelo transponder</div>${pTable(["TESTE Nº","ALTITUDE (PÉS)","PONTO DE TRANSIÇÃO NOMINAL","PONTO DE TRANSIÇÃO ATUAL"],er)}</div><div class="sig"><div>Responsável técnico</div><div>Cliente</div></div></div>`;
 let radio=t.radio.map(r=>[r[0],r[1],r[2]||""]), power=t.power.map(r=>[r[0],r[1],r[2]||""]), other=t.other.map(r=>[r[0],r[1],r[2]||""]), ms=t.modeS.map(r=>[r[0],r[1],r[2]||""]);
 let p4=`<div class="print-page"><div class="print-title">LAUDO TÉCNICO DO TRANSPONDER</div>${metaHTML(s)}<div class="print-grid2"><div><div class="print-section">RÁDIO FREQUÊNCIA DE RESPOSTA</div>${pTable(["TESTE","VALOR REQUERIDO","VALOR ENCONTRADO"],radio)}</div><div><div class="print-section">POTÊNCIA DE PICO DE SAÍDA DE RF</div>${pTable(["TESTE","VALOR","ENCONTRADO"],power)}</div></div><div class="print-grid2"><div><div class="print-section">SUPRESSÃO MODO A</div><div class="print-note">${esc(t.suppression||"")}</div></div><div><div class="print-section">SENSIBILIDADE DO RECEPTOR</div><div class="print-note">${esc(t.sensitivity||"")}</div></div></div><div class="print-section">OUTRAS MEDIÇÕES</div>${pTable(["PARÂMETRO","VALOR REQUERIDO","VALOR ENCONTRADO"],other)}<div class="print-section">SOMENTE PARA TRANSPONDER MODE S</div>${pTable(["TESTE","VALOR / CRITÉRIO","VALOR ENCONTRADO"],ms)}<div class="sig"><div>Responsável técnico</div><div>Cliente</div></div></div>`;
 printRoot.innerHTML=p1+p2+p3+p4;
}

async function downloadReport(){let s=getCurrent();if(!s){alert("Salve a sessão antes de baixar o relatório.");return}collectMeta(s);collectTables(s);saveDB();buildPrint(s);let css="";try{css=await fetch("./style.css").then(r=>r.text())}catch(e){css="@page{size:A4 portrait;margin:0}"}let html=`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Relatório OS ${esc(s.meta.os||"")}</title><style>${css}</style><style>html,body{background:#fff!important;margin:0}#printRoot{display:block!important}.print-page{display:block!important}</style></head><body><div id="printRoot">${printRoot.innerHTML}</div></body></html>`;let blob=new Blob([html],{type:"text/html;charset=utf-8"});let a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`Laudo-Calibracao-OS-${(s.meta.os||"sem-OS").replace(/[^a-z0-9_-]/gi,"_")}.html`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}

document.querySelectorAll(".nav").forEach(b=>b.addEventListener("click",()=>showView(b.dataset.view)));
quickNew.onclick=newSession;newFromList.onclick=newSession;
saveDraft.onclick=()=>saveCurrent(false);finishSession.onclick=()=>saveCurrent(true);saveReport.onclick=()=>saveCurrent(false);printReport.onclick=printReport;
document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{currentReport=b.dataset.report;document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".report").forEach(x=>x.classList.add("hidden"));document.getElementById("report-"+currentReport).classList.remove("hidden")}));
downloadReport.onclick=downloadReport;
exportBackup.onclick=()=>{let blob=new Blob([JSON.stringify(db,null,2)],{type:"application/json"});let a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="aviation-center-sgc-backup-"+new Date().toISOString().slice(0,10)+".json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
importBackup.onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!Array.isArray(x.sessions))throw Error();db=x;saveDB();alert("Backup importado com sucesso.");}catch(_){alert("Backup inválido.")}};r.readAsText(f)};
document.addEventListener("DOMContentLoaded",()=>{updateDashboard();renderSessions();newSession()});

if("serviceWorker" in navigator && location.protocol.startsWith("http")){navigator.serviceWorker.register("./sw.js").catch(()=>{});}
