// Offline PDF generator for Aviation Center Calibrações.
// Uses only standard PDF fonts; no external libraries.
(function(){
  const CP1252={
    '€':0x80,'‚':0x82,'ƒ':0x83,'„':0x84,'…':0x85,'†':0x86,'‡':0x87,'ˆ':0x88,'‰':0x89,'Š':0x8A,'‹':0x8B,'Œ':0x8C,'Ž':0x8E,'‘':0x91,'’':0x92,'“':0x93,'”':0x94,'•':0x95,'–':0x96,'—':0x97,'˜':0x98,'™':0x99,'š':0x9A,'›':0x9B,'œ':0x9C,'ž':0x9E,'Ÿ':0x9F,'º':0xBA,'ª':0xAA,'±':0xB1,'µ':0xB5,'≥':0xB3,'≤':0xB2,'²':0xB2,'³':0xB3,'°':0xB0,'¹':0xB9
  };
  function enc(s){s=String(s??'');let a=[];for(const ch of s){let c=ch.charCodeAt(0);if(c<128|| (c>=160&&c<=255)) a.push(c); else a.push(CP1252[ch]??63);}return new Uint8Array(a)}
  function esc(s){s=String(s??'').replace(/≥/g,'>=').replace(/≤/g,'<=').replace(/±/g,'+/-');return s.replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)')}
  function wrap(text,max){text=String(text??'');if(!text)return [''];let out=[];for(const para of text.replace(/\r/g,'').split('\n')){let words=para.split(/\s+/),line='';if(!words.length){out.push('');continue}for(const w of words){if(!line){line=w;continue}if((line+' '+w).length<=max)line+=' '+w;else{out.push(line);line=w}}out.push(line)}return out}
  function makePDF(pages){
    const objs=[];const add=o=>{objs.push(o);return objs.length};
    const catalog=add('');const pagesObj=add('');const font=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>');
    const pageRefs=[];
    for(const page of pages){let c='q\n1 1 1 rg\n0 0 612 792 re f\n0 0 0 rg\n';c+=page.content+'\nQ';const stream=add(`<< /Length ${enc(c).length} >>\nstream\n${c}\nendstream`);const pref=add(`<< /Type /Page /Parent ${pagesObj} 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${font} 0 R >> >> /Contents ${stream} 0 R >>`);pageRefs.push(pref)}
    objs[catalog-1]=`<< /Type /Catalog /Pages ${pagesObj} 0 R >>`;objs[pagesObj-1]=`<< /Type /Pages /Kids [${pageRefs.map(x=>x+' 0 R').join(' ')}] /Count ${pageRefs.length} >>`;
    let out='%PDF-1.4\n%\xE2\xE3\xCF\xD3\n';let offs=[0];for(let i=0;i<objs.length;i++){offs[i+1]=out.length;out+=(i+1)+' 0 obj\n'+objs[i]+'\nendobj\n'}const xref=out.length;out+='xref\n0 '+(objs.length+1)+'\n0000000000 65535 f \n';for(let i=1;i<offs.length;i++)out+=String(offs[i]).padStart(10,'0')+' 00000 n \n';out+=`trailer\n<< /Size ${objs.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;
    return new Blob([enc(out)],{type:'application/pdf'});
  }
  function pdfFromSession(s){
    const W=592,L=10,TOP=770;const pages=[];let ops='',y=760;
    const txt=(x,yy,t,size=8,bold=false)=>{ops+=`BT /F1 ${size} Tf ${x} ${yy} Td (${esc(t)}) Tj ET\n`};
    const line=(x1,y1,x2,y2)=>{ops+=`0.6 w ${x1} ${y1} m ${x2} ${y2} l S\n`};
    const rect=(x,yy,w,h,fill=false)=>{ops+=fill?`0.96 0.96 0.96 rg ${x} ${yy} ${w} ${h} re f 0 0 0 rg\n`:`${x} ${yy} ${w} ${h} re S\n`};
    const title=t=>{txt(L,y,t,13,true);y-=22};
    const meta=()=>{const m=s.meta||{};const vals=[['CLIENTE',m.cliente],['VALIDADE',m.validade||'2 anos'],['OS',m.os],['DATA',m.data],['FABRICANTE',m.fabricante],['P/N',m.pn],['S/N',m.sn],['PREFIXO',m.prefixo]];const cw=W/4;let rh=25;for(let r=0;r<2;r++){for(let c=0;c<4;c++){let x=L+c*cw,yy=y-r*rh;rect(x,yy-rh,cw,rh);txt(x+4,yy-16,vals[r*4+c][0]+': '+(vals[r*4+c][1]||''),7)} }y-=52};
    const section=t=>{txt(L,y,t,8,true);line(L,y-4,L+W,y-4);y-=16};
    const table=(headers,rows,widths)=>{let x=L;const rowH=18;const fs=6.3;const drawRow=(cells,header)=>{let xx=L;let maxLines=1;cells.forEach((v,i)=>maxLines=Math.max(maxLines,wrap(v,Math.max(8,Math.floor((widths[i]/fs)*1.6))).length));let h=Math.max(rowH,maxLines*8+8);if(y-h<30){pages.push({content:ops});ops='';y=760;title('LAUDO TÉCNICO — continuação');}xx=L;cells.forEach((v,i)=>{rect(xx,y-h,widths[i],h,header);let lines=wrap(v,Math.max(8,Math.floor((widths[i]/fs)*1.55))).slice(0,6);lines.forEach((ln,j)=>txt(xx+2,y-9-j*8,ln,fs,header));xx+=widths[i]});line(L,y-h,L+W,y-h);y-=h};drawRow(headers,true);rows.forEach(r=>drawRow(r,false));y-=4};
    const finish=()=>{if(ops.trim())pages.push({content:ops});ops='';y=760};
    const a=s.reports?.altimetro;
    if(s.selectedReports?.includes('altimetro')){title('LAUDO TÉCNICO DO ALTÍMETRO');meta();section('TESTE DE ATRITO (pressão decrescente)');table(['ALTITUDE (PÉS)','VALOR SEM VIBRAÇÃO','VALOR COM VIBRAÇÃO','TOLERÂNCIA'],(window.ALT_FRICTION||[]).map((v,i)=>[v,a.friction[i].sem||'',a.friction[i].com||'',window.FRICTION_TOL[i]]),[110,150,170,120]);section('ERRO DE ESCALA (pressão decrescente)');table(['ALTITUDE','PRESSÃO EQUIVALENTE (POL HG)','VALOR LIDO','TOL. ±'],(window.ALT_SCALE||[]).map((v,i)=>[v,['31,018','29,921','29,385','28,856','28,335','27,821','26,817','25,842','23,978','22,225','20,577','19,029','17,577','16,216','14,942','13,75'][i],a.scale[i].lido||'',window.SCALE_TOL[i]]),[80,180,150,140]);section('VAZAMENTO DE CAIXA');table(['PRESSÃO','ALTITUDE','VALOR LIDO','TOL. ±'],[[a.leak.pressao,'18000',a.leak.lido||'','100']],[120,100,220,110]);section('ERRO DE ESCALA BARÔMETRO');table(['PRESSÃO','DIFERENÇA','VALOR LIDO'],a.baro.map(r=>[r.valor,r.diferenca,r.lido||'']),[210,180,160]);section('HISTERESE — PRESSÃO CRESCENTE');table(['PONTO DE TESTE','VALOR DECRESCENTE','VALOR CRESCENTE','DIFERENÇA','TOL.'],[['50% altitude máxima (10000 pés)',a.hyst[0].lidoDec||'',a.hyst[0].lidoCresc||'',a.hyst[0].dif||'','75'],['40% altitude máxima (8000 pés)',a.hyst[1].lidoDec||'',a.hyst[1].lidoCresc||'',a.hyst[1].dif||'','75']],[190,115,115,100,72]);finish()}
    if(s.selectedReports?.includes('integracao')){const rows=s.reports.integracao.map(r=>[r.teste,r.altitude,r.altimetro||'',r.transponder||'']);title('LAUDO TÉCNICO INTEGRAÇÃO DO TRANSPONDER E ALTITUDE ENCODER');meta();section('VERIFICAÇÃO DA ALTITUDE TRANSMITIDA PELO TRANSPONDER');table(['TESTE Nº','ALTITUDE (PÉS)','LEITURA DO ALTÍMETRO','LEITURA DO TRANSPONDER'],rows,[65,105,180,242]);finish()}
    if(s.selectedReports?.includes('encoder')){title('LAUDO TÉCNICO DO ENCODER');meta();section('TESTE #6 — VERIFICAÇÃO DA SAÍDA DIGITALIZADA');table(['TESTE Nº','ALTITUDE DE REFERÊNCIA','PONTO DE TRANSIÇÃO NOMINAL','PONTO DE TRANSIÇÃO ATUAL'],s.reports.encoder.map(r=>[r.teste,r.altitude,r.nominal,r.atual||'']),[65,125,180,222]);finish()}
    if(s.selectedReports?.includes('transponder')){const t=s.reports.transponder;title('LAUDO TÉCNICO DO TRANSPONDER');meta();section('RADIO FREQUÊNCIA DE RESPOSTA');table(['TESTE','VALOR REQUERIDO','VALOR ENCONTRADO'],t.radio.map(r=>[r[0],r[1],r[2]||'']),[260,190,142]);section('SUPRESSÃO — MODO 3/A');table(['TESTE','VALOR REQUERIDO','RESULTADO'],t.suppression.map(r=>[r[0],r[1],r[2]||'']),[180,260,152]);section('SENSIBILIDADE DO RECEPTOR');table(['TESTE','VALOR REQUERIDO','VALOR ENCONTRADO'],t.sensitivity.map(r=>[r[0],r[1],r[2]||'']),[200,250,142]);section('POTÊNCIA DE PICO DE SAÍDA');table(['TESTE','VALOR','VALOR ENCONTRADO'],t.power.map(r=>[r[0],r[1],r[2]||'']),[230,210,152]);section('OUTRAS MEDIÇÕES');wrap(t.other||'',95).forEach(ln=>{txt(L,y,ln,7);y-=9});finish();title('LAUDO TÉCNICO DO TRANSPONDER — CONTINUAÇÃO');meta();section('PARÂMETROS — VALOR ENCONTRADO');table(['PARÂMETRO','VALOR REQUERIDO','VALOR ENCONTRADO'],t.reception.map(r=>[r[0],r[1],`${r[2]||''} / ${r[3]||''}`]),[190,210,182]);section('SOMENTE PARA TRANSPONDER MODE S');table(['TESTE','VALOR / CRITÉRIO','VALOR ENCONTRADO'],t.modeS.map(r=>[r[0],r[1],r[2]||'']),[180,300,102]);finish()}
    if(s.selectedReports?.includes('airdata')){const ad=s.reports.airdata;title('LAUDO TÉCNICO DO AIRDATA');meta();section('TESTE #1 — ERRO DE ESCALA (pressão decrescente)');table(['PRESSÃO EQUIV.','ALTITUDE (PÉS)','VALOR LIDO','TOL. ±'],window.AIR_DATA_POINTS.map((p,i)=>[p[0],p[1],ad.rows[i]?.valor||'',p[2]]),[145,130,190,117]);section('TESTE #4 — VAZAMENTO DA LINHA');table(['PRESSÃO','ALTITUDE','VALOR LIDO','TOL.'],[['13.750','20.000',ad.leak||'','± 100']],[145,130,190,117]);finish()}
    if(s.observacoesAjustes){if(!pages.length&& !ops) {title('OBSERVAÇÕES / AJUSTES')} else {section('OBSERVAÇÕES / AJUSTES')} wrap(s.observacoesAjustes,115).forEach(ln=>{txt(L,y,ln,7);y-=9});}
    finish();return makePDF(pages);
  }
  window.AviationPDF={pdfFromSession};
})();
